### ISSUE TITLE
Relative references in $ref are not supported

### ISSUE THREAD

**Issue by tnmtechnologies** [eclipse-vertx/vertx-openapi#74]
### Version

4.5.8

### Context

Relative references in $ref are not supported (see OpenAPI spec https://spec.openapis.org/oas/latest.html#relative-references-in-uris) while it worked well with previous OpenAPI library.

The following exception is thrown:

> java.lang.UnsupportedOperationException: Can't resolve 'the relative reference to a OpenAPI file ', only internal refs are supported.
        at io.vertx.json.schema.impl.JsonRef.resolveUri(JsonRef.java:344)
        at io.vertx.json.schema.impl.JsonRef.resolve(JsonRef.java:211)
        at io.vertx.json.schema.impl.SchemaRepositoryImpl.resolve(SchemaRepositoryImpl.java:243)
        at io.vertx.openapi.contract.OpenAPIVersion.lambda$resolve$3(OpenAPIVersion.java:86)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:191)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:279)
        at io.vertx.core.impl.ContextImpl.lambda$internalExecuteBlocking$2(ContextImpl.java:210)
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)

### Do you have a reproducer?

No

* Link to github project/gist

### Extra

* Anything that can be relevant such as OS version, JVM version

**Comment by pk-work** [comment]
Due to security reasons we decided that files must be provided upfront. Maybe we could add a method which parses the OpenAPI files, follow the relative links and create the required additionalContractFiles Map. But I don't think that is something I will develop in the future.

If you want to provide such a feature, I would support it.

**Comment by tsegismont** [comment]
@pk-work as discussed off-list, I will a give a shot to implementing this feature. Below is a summary of the plan as I understand it.

We should parse the contract, follow the relative links and create the required additionalContractFiles map. But we should also modify the content of the contract, because vert.x json schema will tolerate only internal references.

For example, we could transform a relative reference like this `nested/schema.yaml` into absolute file urls like this one: `file:///path/to/my/openapi/files/nested/schema.yaml` (assuming the relative reference is resolved when in `/path/to/my/openapi/files`)

**Comment by pk-work** [comment]
Yes, the contract must be modified, because the relative link must be replaced with the "key" from the additional contract map. Here is an example [1]  yaml and the related test [2] in which the map is created.

[1] https://github.com/eclipse-vertx/vertx-openapi/blob/main/src/test/resources/io/vertx/tests/contract/from_with_path_and_additional_files/petstore.yaml

[2] https://github.com/eclipse-vertx/vertx-openapi/blob/1efa73c0a28a1e25fdf0957c4ad36fa4e4adef43/src/test/java/io/vertx/tests/contract/OpenAPIContractBuilderTest.java#L72

**Comment by tsegismont** [comment]
Thanks @pk-work 

I believe it should work if the replacement is an absolute file URI like `file:///path/to/my/openapi/files/nested/schema.yaml`
Is it fine with you or can you think about any problem (for example exposing a file system hierarchy publicly) ?

**Comment by pk-work** [comment]
If you would expose the full path publicly it may is an issue, because it can tell an attacker which OS or web server you use. But in this case we replace relative links with absolute ones during the contract "construction". I'm pretty sure this is not exposed somewhere, so it shouldn't be any problem.

**Comment by tsegismont** [comment]
@tnmtechnologies have you tried a bundler tool like Redocly:

 ```shell
npx @redocly/cli bundle contract.yaml --output bundled.yaml
```

@pk-work any experience with that?

**Comment by tsegismont** [comment]
In fact, with `swagger-parser`:

```xml
<dependencies>
    <dependency>
        <groupId>io.swagger.parser.v3</groupId>
        <artifactId>swagger-parser</artifactId>
        <version>2.1.20</version>
    </dependency>
</dependencies>
```

Creating a bundled contract is relatively straightforward:

```java
package org.example.myproject;

import io.swagger.v3.core.util.Yaml;
import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.parser.OpenAPIV3Parser;
import io.swagger.v3.parser.core.models.ParseOptions;
import io.swagger.v3.parser.core.models.SwaggerParseResult;

import java.nio.file.Files;
import java.nio.file.Paths;

public class OpenApiBundler {
  public static void main(String[] args) throws Exception {
    String inputPath = "src/test/resources/io/vertx/tests/contract/relative_refs/cross_refs/openapi.yaml";

    ParseOptions options = new ParseOptions();
    // This resolves external files and moves them into the 'components' section
    options.setResolve(true);

    // This keeps the $ref but points it to the new local component.
    options.setResolveFully(false);

    SwaggerParseResult result = new OpenAPIV3Parser().readLocation(inputPath, null, options);
    OpenAPI openAPI = result.getOpenAPI();

    if (openAPI != null) {
      String bundledYaml = Yaml.pretty().writeValueAsString(openAPI);
      Files.write(Paths.get("bundled-openapi.yaml"), bundledYaml.getBytes());
    } else {
      System.err.println("Errors found: " + result.getMessages());
    }
  }
}
```

And then this could be embedded in a Maven plugin (after updating the code to take arguments):

```xml
<plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>exec-maven-plugin</artifactId>
    <version>3.1.0</version>
    <executions>
        <execution>
            <id>bundle-openapi</id>
            <phase>generate-resources</phase>
            <goals>
                <goal>java</goal>
            </goals>
            <configuration>
                <mainClass>org.example.myproject</mainClass>
                <arguments>
                    <argument>src/main/resources/openapi.yaml</argument>
                    <argument>${project.build.directory}/bundled-openapi.yaml</argument>
                </arguments>
            </configuration>
        </execution>
    </executions>
</plugin>
```

**Comment by pk-work** [comment]
Yes, I have experience with redocly. I think I even created some test resources [1] in vertx-json-schema with redocly.

But calling redocly from Java during contract construction is most probably not an option. I also don't get completely how a maven plugin can solve the issue. Because the contract is not always available on build time.


[1] https://github.com/eclipse-vertx/vertx-json-schema/blob/master/src/test/resources/resolve/guestbook_bundle.json

**Comment by tsegismont** [comment]
> Because the contract is not always available on build time.

Oh right, that's a very good point. Having a dependency on Swagger parser at build time is not big deal IMO, but since the contracts may not be available until the application starts, we can't rely on this.

**Comment by AdrianVasiliu** [comment]
Thanks @tsegismont for the redocly-cli [suggestion](https://github.com/eclipse-vertx/vertx-openapi/issues/74#issuecomment-3805548488)! I gave a quick try to `redocly bundle` with our openapi with many relative refs - it did work as expected for bundling together a unique large openapi file. 
In our case, the openapis are known at the build time of a java project, so this may be applicable as a pre-build step.

That said, we currently use vertx 4.5.22, and we don't face the exception mentioned in the present issue (`java.lang.UnsupportedOperationException: Can't resolve 'the relative reference to a OpenAPI file ', only internal refs are supported.`). Instead, we face:
```
Caused by: io.vertx.ext.web.openapi.RouterBuilderException: Cannot load the spec in path <our path to openapi with relative refs>
at io.vertx.ext.web.openapi.RouterBuilderException.createInvalidSpecFile([RouterBuilderException.java:50](http://routerbuilderexception.java:50/)) ~[vertx-web-openapi-4.5.18.jar:4.5.18]
... 42 more
Caused by: java.lang.IllegalStateException: Recursive update
at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source) ~[?:?]
at io.vertx.ext.web.openapi.impl.OpenAPIHolderImpl.resolveExternalRef([OpenAPIHolderImpl.java:266](http://openapiholderimpl.java:266/)) ~[vertx-web-openapi-4.5.18.jar:4.5.18]
at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source) ~[?:?]
at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
at io.vertx.ext.web.openapi.impl.OpenAPIHolderImpl.walkAndSolve([OpenAPIHolderImpl.java:207](http://openapiholderimpl.java:207/)) ~[vertx-web-openapi-4.5.18.jar:4.5.18]
at io.vertx.ext.web.openapi.impl.OpenAPIHolderImpl.lambda$null$5([OpenAPIHolderImpl.java:271](http://openapiholderimpl.java:271/)) ~[vertx-web-openapi-4.5.18.jar:4.5.18]
at io.vertx.core.impl.future.Composition.onSuccess([Composition.java:38](http://composition.java:38/)) ~[vertx-core-4.5.18.jar:4.5.18]
... 15 more
```

This hurts intermittently. (The above stack is from the past, at a time we used vertx 4.5.18.)
It's possible, though, that this other issue also goes away with bundling the openapi - a partial manual bundling a year or so ago did reduce the frequency of occurrence of the issue.

**Comment by tsegismont** [comment]
> I also don't get completely how a maven plugin can solve the issue. Because the contract is not always available on build time.

@pk-work I may not have expressed clearly my thoughts. I was evaluating the opportunity of implementing this feature if a build-time solution (Redocly CLI or Swagger Parser) fits the need of @AdrianVasiliu and @tnmtechnologies

**Comment by tsegismont** [comment]
> That said, we currently use vertx 4.5.22, and we don't face the exception mentioned in the present issue

@AdrianVasiliu I filed https://github.com/vert-x3/vertx-web/issues/2844 and sent PR https://github.com/vert-x3/vertx-web/pull/2845 for this issue (it's related to another module that is no longer available in Vert.x 5)

**Comment by AdrianVasiliu** [comment]
@tsegismont Thanks a lot.  I followed up [here](https://github.com/vert-x3/vertx-web/pull/2845#issuecomment-3823459360).

**Comment by lukasjelonek** [comment]
Hi everyone,

I stumbled upon this problem in vertx 5.0.10 and sketched a vertx-only solution to resolve relative $refs:

```java
  @Test
  void load_contract_with_relative_refs_should_work(Vertx vertx) {
    var contractJson        = Utils.readYamlOrJson(vertx, "openapi.yaml").await();
    var additionalContracts = new HashMap<String, JsonObject>();
    replaceLocalRefsWithUris(vertx, contractJson, additionalContracts);

    var contract = OpenAPIContract.from(vertx, contractJson, additionalContracts).await();
    var rb       = RouterBuilder.create(vertx, contract);
  }

  private void replaceLocalRefsWithUris(Vertx vertx, JsonObject object, Map<String, JsonObject> additionalFiles) {
    for (var f : object.fieldNames()) {
      if ("$ref".equals(f)) {
        var ref = object.getString(f);
        if (isRelativePath(ref)) {
          var uri = "local-refs://" + ref;
          object.put("$ref", uri);
          if (!additionalFiles.containsKey(uri)) {
            var p        = getPath(ref);
            var contract = Utils.readYamlOrJson(vertx, p).await();
            additionalFiles.put(uri, contract);
          }
        }
      } else if (object.getValue(f) instanceof JsonObject obj) {
        replaceLocalRefsWithUris(vertx, obj, additionalFiles);
      } else if (object.getValue(f) instanceof JsonArray arr) {
        replaceLocalRefsWithUris(vertx, arr, additionalFiles);
      }
    }
  }

  private void replaceLocalRefsWithUris(Vertx vertx, JsonArray array, Map<String, JsonObject> additionalFiles) {
    for (var c : array) {
      if (c instanceof JsonObject j) {
        replaceLocalRefsWithUris(vertx, j, additionalFiles);
      } else if (c instanceof JsonArray a) {
        replaceLocalRefsWithUris(vertx, a, additionalFiles);
      }
    }
  }

  private boolean isRelativePath(String p) {
    return p.startsWith("./");
  }

  private String getPath(String ref) {
    var s = ref.split("#");
    return s[0];
  }
```

This code is far from production ready, as it only works on the first level of dependencies and the local path definition is quite narrow, but these should be minor issues.

**Comment by lukasjelonek** [comment]
@pk-work is there interest to have this feature in vertx-openapi? If so I'd like to contribute. 

It could be added to the OpenAPIContractBuilder, for example as `builder.setResolveLocalReferencedSchemas(true)`. I now have a solution that resolves all relative referenced contracts recursively. The only caveat in my implementation at the moment is that I use `Future.await()` in a single place that must be replaced before handing it over to the public.

**Comment by pk-work** [comment]
Hi @lukasjelonek, yes I think there is interest to have this feature. Maybe some things I'd like to discuss.

1. If you have a contract with relative paths, it would always fail with the current implementation, right? Would it make sense to resolve relative paths by default? The downside, however, is that we might put a lot of effort into looping a contract without local references. Maybe a string search for "./" makes sense to check whether it's worth it or not.
2. The `OpenAPIContractBuilder` is already quite large. That's why I would prefer, if possible, to outsource the code to a separate class. Maybe there's a way to do this without it seeming artificial.

**Comment by lukasjelonek** [comment]
1. From my gut I would use it as an optional feature. Then everyone who cares can activate it and the others will get the same behaviour as now. But in the end it comes down to preference and a decision. In my new implementation I decide whether a $ref is relative or not by checking if it has a schema or not.
2. At the moment I have everything in a single class. The OpenAPIContractBuilder would only get the additional field and then would use the additional class to resolve the local refs.  

I will attached my current implementation here. At the moment it constructs the whole contract, but eventually it should return the contract and the additional contracts, so that it can be combined with the existing factory/builder options. 

```java
/**
 * Loads a local openapi contract and resolves all local refs.
 */
public class OpenApiContractLoader {

  private final Vertx vertx;

  private OpenApiContractLoader(Vertx vertx) {
    this.vertx = vertx;
  }

  public static OpenApiContractLoader create(Vertx vertx) {
    return new OpenApiContractLoader(vertx);
  }

  /**
   * @param path The path in the filessystem to a contract.
   * @param uri  The uri of the ref if it is a replaced local ref
   */
  private record Entry(String path, Optional<String> uri) {
    static Entry root(String path) {
      return new Entry(path, Optional.empty());
    }

    static Entry ref(String path, String uri) {
      return new Entry(path, Optional.of(uri));
    }
  }

  /**
   * @param contract  The parsed contract.
   * @param localRefs The local refs that have been replaced with local-ref:// uris
   */
  private record Result(Entry entry, JsonObject contract, Set<Entry> localRefs) {
  }

  private final class ProcessingContext {
    private JsonObject                     contract;
    private final Deque<Entry>             toResolve           = new ArrayDeque<>();
    private final Map<String, JsonObject>  additionalContracts = new HashMap<>();
    private final Promise<OpenAPIContract> promise             = Promise.promise();
  }

  public Future<OpenAPIContract> loadContractWithResolvedLocalReferences(String path) {
    var ctx = new ProcessingContext();
    ctx.toResolve.add(Entry.root(path));

    readContractAndFixLocalRefs(ctx.toResolve.poll())
        .onSuccess(result -> contractProcessed(ctx, result))
        .onFailure(ctx.promise::fail);

    return ctx.promise.future();
  }

  private void contractProcessed(ProcessingContext ctx, Result result) {
    if (result.entry.uri.isEmpty()) {
      ctx.contract = result.contract;
    } else {
      ctx.additionalContracts.put(result.entry.uri.get(), result.contract);
    }
    for (var r : result.localRefs) {
      // only the root contract should not have a uri, so it is safe to retrieve the uri without check
      var uri = r.uri.get();
      if (!ctx.additionalContracts.containsKey(uri)) {
        // avoid duplicates by adding a placeholder that will be resolved later when the queue is processed
        ctx.additionalContracts.put(uri, null);
        ctx.toResolve.add(r);
      }
    }
    if (ctx.toResolve.isEmpty()) {
      OpenAPIContract.from(vertx, ctx.contract, ctx.additionalContracts)
          .onSuccess(ctx.promise::complete)
          .onFailure(ctx.promise::fail);
    } else {
      readContractAndFixLocalRefs(ctx.toResolve.poll())
          .onSuccess(r -> contractProcessed(ctx, r))
          .onFailure(ctx.promise::fail);
    }
  }

  private Future<Result> readContractAndFixLocalRefs(Entry entry) {
    return Utils.readYamlOrJson(vertx, entry.path)
        .map(contract -> {
          var root        = Paths.get(entry.path).getParent();
          var localReferences = new HashSet<Entry>();
          traverse(root, contract, localReferences);
          return new Result(entry, contract, localReferences);
        });
  }

  private void traverse(Path root, JsonObject object, Set<Entry> replacedRefs) {
    for (var f : object.fieldNames()) {
      if ("$ref".equals(f)) {
        var ref = object.getString(f);
        if (!hasSchema(ref)) {
          var path = root.resolve(ref).normalize();
          var uri  = "local-refs://" + path.toString();
          object.put("$ref", uri);
          var entry = Entry.ref(path.toString(), uri);
          replacedRefs.add(entry);
        }
      } else if (object.getValue(f) instanceof JsonObject obj) {
        traverse(root, obj, replacedRefs);
      } else if (object.getValue(f) instanceof JsonArray arr) {
        traverse(root, arr, replacedRefs);
      }
    }
  }

  private void traverse(Path root, JsonArray array, Set<Entry> replacedRefs) {
    for (var c : array) {
      if (c instanceof JsonObject j) {
        traverse(root, j, replacedRefs);
      } else if (c instanceof JsonArray a) {
        traverse(root, a, replacedRefs);
      }
    }
  }

  // uri schema regex, based on https://datatracker.ietf.org/doc/html/rfc3986#section-3.1
  private static Pattern schema = Pattern.compile("^\\w[\\w\\d.+-]*:");

  private boolean hasSchema(String ref) {
    return schema.matcher(ref).matches();
  }
}
```
